apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  outbound:
    serviceReferences:
    - name: choreo:///binoydev/yasitha-project/tyfagy/8b1c3/v1/PUBLIC
      connectionConfig: 01eefc72-5c4b-1b20-bf50-2f57c47f6f1b
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL
