apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  outbound:
    serviceReferences:
    - name: choreo:///binoydev/yasitha-project/tyfagy/8b1c3/v1/PUBLIC
      connectionConfig: 01eefc0b-3d66-1056-b28d-f7ec60c623e6
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL
