apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  outbound:
    serviceReferences:
      - name: choreo:///binoydev/yasitha-project/ckddjo/8b1c3/v1.0/PUBLIC
        connectionConfig: 01eef0ab-1193-13d6-bb2f-4cafb2095383
        env:
          - from: ServiceURL
            to: SVC_URL
