openapi: 3.0.0
info:
  title: Greeter API
  version: 1.0.0
  description: This is a sample server for greeting.

paths:
  /greeter/greet:
    get:
      summary: Greet a user
      description: Greets the user with a message
      parameters:
        - in: query
          name: name
          schema:
            type: string
            default: Stranger
          description: Name of the user
          required: false
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: Hello, Stranger! You are connected to port 9090.
