apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  outbound:
    serviceReferences:
    - name: choreo:///binoydev/yasitha-project/tyfagy/8b1c3/v1/PUBLIC
      connectionConfig: 01eefba5-fc87-1d50-a761-1ca9e9be7e3c
      env:
      - from: ServiceURL
        to: SVC_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL


