apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: Ballerina endpoint
      # +required Numeric port value that gets exposed via this endpoint
      port: 8090
      # +required Type of the traffic this endpoint is accepting. Example: REST, GraphQL, etc.
      # Allowed values: REST, GraphQL, GRPC
      type: REST
      # +optional Network level visibility of this endpoint. Defaults to Project
      # Accepted values: Project|Organization|Public.
      networkVisibility: Public
      # +optional Context (base path) of the API that is exposed via this endpoint.
      # This is mandatory if the endpoint type is set to REST or GraphQL.
      context: /
      # +optional Path to the schema definition file. Defaults to wild card route if not provided
      # This is only applicable to REST endpoint types.
      # The path should be relative to the docker context.
      schemaFilePath: sample_openapi.yaml
  outbound:
    serviceReferences:
    - name: choreo:///yasithaorg/kwav/jhibrv/8b1c3/v1.0/PUBLIC
      connectionConfig: 01ef02d5-f8f6-1fb6-af0a-5e7078f666c8
      env:
      - from: ServiceURL
        to: SERVICE_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL

